id: detector_243027
name: 智能家居
name[zh]: 检测器 243027
version: 4.8.2
author: MaixHub@Sipeed Ltd
icon: app.png
desc: 检测火焰和人，以及手势识别
exclude:
  - __pycache__
  - build
  - dist
  - .gitignore
files:
  - app.yaml
  - main_gesture.py
  - main.py
  - main.py.backup
  - model_243027.cvimodel
  - model_243027.mud
  - report.json
  - test_example.py
  - test_minimal.py
  - test_simple.py
